import 'data/models/course_model.dart';

/// Dữ liệu khóa học hardcode ở data layer — mock approach.
///
/// Sau M3, file này không trả về domain entity trực tiếp nữa.
/// Nó trả về `CourseModel` để giả lập dữ liệu thô từ API/local database.
///
/// Vấn đề cần quan sát:
/// - `status` và `level` vẫn là String giống dữ liệu ngoài hệ thống.
/// - Mapper sẽ chuyển các String này sang enum của domain.
/// - Nếu sau này đổi sang API thật, UI/domain không nên phải sửa theo.
const List<CourseModel> mockCourseModels = [
  CourseModel(
    id: 'crs_01',
    title: 'Flutter & Dart: Xây dựng ứng dụng từ A-Z',
    description:
        'Khóa học toàn diện về Flutter và Dart dành cho người mới bắt đầu. Bạn sẽ xây dựng 5 ứng dụng thực tế và nắm vững kiến trúc BLoC.',
    instructorName: 'Nguyễn Minh Khoa',
    categoryName: 'Lập trình',
    status: 'published',
    level: 'beginner',
    price: 499000,
    originalPrice: 999000,
    rating: 4.8,
    reviewCount: 412,
    enrollmentCount: 1850,
    durationMinutes: 1440,
    lessonCount: 96,
    tags: ['flutter', 'dart', 'mobile', 'bloc'],
  ),
  CourseModel(
    id: 'crs_02',
    title: 'Clean Architecture trong Flutter',
    description:
        'Học cách tổ chức code Flutter theo Clean Architecture, áp dụng SOLID principles và viết unit test chuyên nghiệp.',
    instructorName: 'Nguyễn Minh Khoa',
    categoryName: 'Lập trình',
    status: 'published',
    level: 'advanced',
    price: 699000,
    originalPrice: 1299000,
    rating: 4.9,
    reviewCount: 287,
    enrollmentCount: 960,
    durationMinutes: 1080,
    lessonCount: 72,
    tags: ['flutter', 'clean-architecture', 'solid', 'testing'],
  ),
  CourseModel(
    id: 'crs_03',
    title: 'Python cho Data Science',
    description:
        'Từ cơ bản Python đến phân tích dữ liệu với Pandas, NumPy, Matplotlib và Scikit-learn.',
    instructorName: 'Nguyễn Minh Khoa',
    categoryName: 'Khoa học dữ liệu',
    status: 'published',
    level: 'intermediate',
    price: 599000,
    originalPrice: 1099000,
    rating: 4.7,
    reviewCount: 531,
    enrollmentCount: 2340,
    durationMinutes: 1320,
    lessonCount: 88,
    tags: ['python', 'data-science', 'pandas', 'machine-learning'],
  ),
  CourseModel(
    id: 'crs_04',
    title: 'UI/UX Design Fundamentals',
    description:
        'Nắm vững nguyên lý thiết kế, quy trình Design Thinking và sử dụng Figma để tạo ra sản phẩm thực tế.',
    instructorName: 'Trần Thị Lan Anh',
    categoryName: 'Thiết kế UI/UX',
    status: 'published',
    level: 'beginner',
    price: 549000,
    originalPrice: 999000,
    rating: 4.9,
    reviewCount: 874,
    enrollmentCount: 4120,
    durationMinutes: 960,
    lessonCount: 64,
    tags: ['ui-ux', 'figma', 'design-thinking', 'prototyping'],
  ),
  CourseModel(
    id: 'crs_05',
    title: 'Advanced Figma: Design System & Components',
    description:
        'Khóa học nâng cao về Figma, xây dựng design system quy mô lớn, quản lý component library.',
    instructorName: 'Trần Thị Lan Anh',
    categoryName: 'Thiết kế UI/UX',
    status: 'published',
    level: 'advanced',
    price: 799000,
    originalPrice: 1499000,
    rating: 4.8,
    reviewCount: 203,
    enrollmentCount: 780,
    durationMinutes: 720,
    lessonCount: 48,
    tags: ['figma', 'design-system', 'components'],
  ),
  CourseModel(
    id: 'crs_06',
    title: 'Machine Learning với TensorFlow',
    description:
        'Hiểu sâu về các thuật toán ML và triển khai mô hình với TensorFlow 2.x và Keras.',
    instructorName: 'Nguyễn Minh Khoa',
    categoryName: 'Khoa học dữ liệu',
    status: 'published',
    level: 'advanced',
    price: 899000,
    originalPrice: 1699000,
    rating: 4.6,
    reviewCount: 318,
    enrollmentCount: 1140,
    durationMinutes: 1560,
    lessonCount: 104,
    tags: ['machine-learning', 'tensorflow', 'keras', 'deep-learning'],
  ),
  CourseModel(
    id: 'crs_07',
    title: 'Khởi nghiệp từ 0: Từ ý tưởng đến sản phẩm',
    description:
        'Hướng dẫn thực tiễn để biến ý tưởng kinh doanh thành sản phẩm MVP và thu hút đầu tư.',
    instructorName: 'Lê Hoàng Phúc',
    categoryName: 'Kinh doanh',
    status: 'published',
    level: 'beginner',
    price: 449000,
    originalPrice: 799000,
    rating: 4.7,
    reviewCount: 456,
    enrollmentCount: 1980,
    durationMinutes: 840,
    lessonCount: 56,
    tags: ['startup', 'mvp', 'business-model', 'fundraising'],
  ),
  CourseModel(
    id: 'crs_08',
    title: 'Digital Marketing toàn diện',
    description:
        'Chiến lược marketing số bao gồm SEO, Google Ads, Facebook Ads, Email Marketing và Content Marketing.',
    instructorName: 'Lê Hoàng Phúc',
    categoryName: 'Kinh doanh',
    status: 'published',
    level: 'intermediate',
    price: 599000,
    originalPrice: 1199000,
    rating: 4.5,
    reviewCount: 289,
    enrollmentCount: 1320,
    durationMinutes: 1200,
    lessonCount: 80,
    tags: ['digital-marketing', 'seo', 'google-ads', 'facebook-ads'],
  ),
  CourseModel(
    id: 'crs_09',
    title: 'Node.js & Express: REST API từ A-Z',
    description:
        'Xây dựng REST API mạnh mẽ với Node.js, Express, MongoDB và triển khai lên cloud.',
    instructorName: 'Nguyễn Minh Khoa',
    categoryName: 'Lập trình',
    status: 'published',
    level: 'intermediate',
    price: 549000,
    originalPrice: 999000,
    rating: 4.7,
    reviewCount: 374,
    enrollmentCount: 1560,
    durationMinutes: 1080,
    lessonCount: 72,
    tags: ['nodejs', 'express', 'mongodb', 'rest-api'],
  ),
  CourseModel(
    id: 'crs_10',
    title: 'React Native: Ứng dụng đa nền tảng',
    description:
        'Phát triển ứng dụng iOS và Android với React Native và Expo. Từ cơ bản đến publish lên store.',
    instructorName: 'Nguyễn Minh Khoa',
    categoryName: 'Lập trình',
    status: 'draft',
    level: 'intermediate',
    price: 649000,
    originalPrice: 1299000,
    rating: 0,
    reviewCount: 0,
    enrollmentCount: 0,
    durationMinutes: 1200,
    lessonCount: 80,
    tags: ['react-native', 'expo', 'mobile', 'ios', 'android'],
  ),
  CourseModel(
    id: 'crs_11',
    title: 'Figma to Flutter: Chuyển đổi thiết kế thành code',
    description:
        'Khóa học kết hợp giữa design và development, học cách chuyển đổi thiết kế Figma thành ứng dụng Flutter.',
    instructorName: 'Trần Thị Lan Anh',
    categoryName: 'Thiết kế UI/UX',
    status: 'draft',
    level: 'intermediate',
    price: 749000,
    originalPrice: 1399000,
    rating: 0,
    reviewCount: 0,
    enrollmentCount: 0,
    durationMinutes: 900,
    lessonCount: 60,
    tags: ['figma', 'flutter', 'design-to-code'],
  ),
  CourseModel(
    id: 'crs_12',
    title: 'Tư duy dữ liệu với SQL & Power BI',
    description:
        'Học SQL từ cơ bản đến nâng cao, kết hợp Power BI để tạo dashboard báo cáo kinh doanh chuyên nghiệp.',
    instructorName: 'Nguyễn Minh Khoa',
    categoryName: 'Khoa học dữ liệu',
    status: 'draft',
    level: 'beginner',
    price: 499000,
    originalPrice: 899000,
    rating: 0,
    reviewCount: 0,
    enrollmentCount: 0,
    durationMinutes: 1080,
    lessonCount: 72,
    tags: ['sql', 'power-bi', 'data-analysis'],
  ),
  CourseModel(
    id: 'crs_13',
    title: 'Kỹ năng thuyết trình & giao tiếp chuyên nghiệp',
    description:
        'Phát triển kỹ năng thuyết trình trước đám đông, kỹ năng giao tiếp trong môi trường công sở và kỹ năng đàm phán.',
    instructorName: 'Lê Hoàng Phúc',
    categoryName: 'Phát triển cá nhân',
    status: 'published',
    level: 'beginner',
    price: 349000,
    originalPrice: 699000,
    rating: 4.6,
    reviewCount: 523,
    enrollmentCount: 2190,
    durationMinutes: 600,
    lessonCount: 40,
    tags: ['soft-skills', 'presentation', 'communication'],
  ),
  CourseModel(
    id: 'crs_14',
    title: 'iOS Development với Swift & SwiftUI',
    description:
        'Phát triển ứng dụng iOS native với Swift và SwiftUI. Khóa học này đã bị ngừng cập nhật.',
    instructorName: 'Nguyễn Minh Khoa',
    categoryName: 'Lập trình',
    status: 'archived',
    level: 'intermediate',
    price: 599000,
    originalPrice: 999000,
    rating: 4.3,
    reviewCount: 198,
    enrollmentCount: 870,
    durationMinutes: 1200,
    lessonCount: 80,
    tags: ['ios', 'swift', 'swiftui', 'apple'],
  ),
  CourseModel(
    id: 'crs_15',
    title: 'WordPress cơ bản: Tạo website không cần code',
    description:
        'Xây dựng website chuyên nghiệp với WordPress, Elementor và WooCommerce. Khóa học cũ, nội dung lỗi thời.',
    instructorName: 'Lê Hoàng Phúc',
    categoryName: 'Lập trình',
    status: 'archived',
    level: 'beginner',
    price: 299000,
    originalPrice: 599000,
    rating: 4.1,
    reviewCount: 412,
    enrollmentCount: 3100,
    durationMinutes: 720,
    lessonCount: 48,
    tags: ['wordpress', 'elementor', 'woocommerce', 'no-code'],
  ),
  CourseModel(
    id: 'crs_16',
    title: 'Quản lý dự án theo Agile & Scrum',
    description:
        'Nắm vững phương pháp Agile và Scrum để quản lý dự án phần mềm hiệu quả.',
    instructorName: 'Lê Hoàng Phúc',
    categoryName: 'Kinh doanh',
    status: 'archived',
    level: 'intermediate',
    price: 499000,
    originalPrice: 999000,
    rating: 4.4,
    reviewCount: 176,
    enrollmentCount: 640,
    durationMinutes: 780,
    lessonCount: 52,
    tags: ['agile', 'scrum', 'project-management'],
  ),
];
